# Generated by Django 2.2.7 on 2019-11-14 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='', max_length=60)),
                ('Year', models.CharField(default='', max_length=10)),
                ('Genre', models.CharField(default='', max_length=10)),
                ('Plot', models.TextField(default='')),
                ('Poster', models.TextField(default='')),
                ('imdbRating', models.PositiveIntegerField(default=1)),
                ('imdbVotes', models.CharField(default='', max_length=30)),
                ('imdbID', models.CharField(default='', max_length=15)),
                ('totalSeasons', models.PositiveIntegerField(default=1)),
                ('justWatchUrl', models.CharField(default='', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='', max_length=100)),
                ('Released', models.CharField(default='', max_length=15)),
                ('Season', models.PositiveIntegerField(default=1)),
                ('Episode', models.PositiveIntegerField(default=10)),
                ('Runtime', models.CharField(default='', max_length=15)),
                ('Plot', models.TextField(default='')),
                ('Poster', models.TextField(default='')),
                ('imdbRating', models.PositiveIntegerField(default=1)),
                ('imdbVotes', models.CharField(default='', max_length=30)),
                ('imdbID', models.CharField(default='', max_length=15)),
                ('imdbSeriesID', models.CharField(default='', max_length=15)),
                ('justWatchUrl', models.CharField(default='', max_length=60)),
                ('show', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='holiday_specials.Show')),
            ],
        ),
    ]
