# Generated by Django 2.2.7 on 2019-11-06 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('holiday_specials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='show',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='holiday_specials.Show'),
            preserve_default=False,
        ),
    ]
