# Generated by Django 2.2.7 on 2019-11-06 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday_specials', '0002_episode_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='episode',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='episode',
            name='season',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='show',
            name='genre',
            field=models.CharField(choices=[('comedy', 'COMEDY'), ('drama', 'DRAMA')], default='comedy', max_length=6),
        ),
    ]
