# Generated by Django 2.2.7 on 2019-11-13 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday_specials', '0004_auto_20191107_2247'),
    ]

    operations = [
        migrations.RenameField(
            model_name='episode',
            old_name='description',
            new_name='Plot',
        ),
        migrations.RenameField(
            model_name='episode',
            old_name='episode',
            new_name='Season',
        ),
        migrations.RenameField(
            model_name='episode',
            old_name='name',
            new_name='Title',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='description',
            new_name='Plot',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='image_url',
            new_name='Poster',
        ),
        migrations.RenameField(
            model_name='show',
            old_name='name',
            new_name='Title',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='date',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='season',
        ),
        migrations.RemoveField(
            model_name='show',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='show',
            name='imdb_url',
        ),
        migrations.RemoveField(
            model_name='show',
            name='streaming_on',
        ),
        migrations.AddField(
            model_name='episode',
            name='Episode',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AddField(
            model_name='episode',
            name='Poster',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='episode',
            name='Released',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='episode',
            name='Runtime',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='episode',
            name='imdbID',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='episode',
            name='imdbRating',
            field=models.PositiveIntegerField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='episode',
            name='imdbSeriesID',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='episode',
            name='imdbVotes',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='episode',
            name='justWatchUrl',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='show',
            name='Genre',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='show',
            name='Year',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='show',
            name='imdbID',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='show',
            name='imdbRating',
            field=models.PositiveIntegerField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='show',
            name='imdbVotes',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='show',
            name='justWatchUrl',
            field=models.CharField(default='', max_length=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='show',
            name='totalSeasons',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
