# Generated by Django 2.2.7 on 2019-11-13 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday_specials', '0005_auto_20191113_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='imdbRating',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='show',
            name='imdbRating',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
