# Generated by Django 2.2.7 on 2019-11-13 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holiday_specials', '0006_auto_20191113_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='Plot',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='episode',
            name='Poster',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='episode',
            name='Released',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='episode',
            name='Runtime',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='episode',
            name='Title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='episode',
            name='imdbID',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='episode',
            name='imdbSeriesID',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='episode',
            name='imdbVotes',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='episode',
            name='justWatchUrl',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='show',
            name='Genre',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='show',
            name='Plot',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='show',
            name='Poster',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='show',
            name='Title',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='show',
            name='Year',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='show',
            name='imdbID',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='show',
            name='imdbVotes',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='show',
            name='justWatchUrl',
            field=models.CharField(default='', max_length=60),
        ),
    ]
